go:
  version: 1.13.1
repository:
  path: github.com/ppanyukov/go-boot
build:
  binaries:
    - name: ./bin/go-boot
      path: ./cmd/go-boot
  flags: -a -tags netgo
  ldflags: |
    -X {{repoPath}}/pkg/version.Version={{.Version}}
    -X {{repoPath}}/pkg/version.Revision={{.Revision}}
    -X {{repoPath}}/pkg/version.Branch={{.Branch}}
    -X {{repoPath}}/pkg/version.BuildUser={{user}}@{{host}}
    -X {{repoPath}}/pkg/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
  platforms:
    - linux/amd64
    - darwin/amd64
    - linux/arm64
    - windows/amd64
    - freebsd/amd64
